### ISSUE TITLE
启动 Mesh 模式失败

### ISSUE THREAD

**Issue by ltinyho** [nocalhost/nocalhost#1340]
**What happened**:
启动 Mesh 模式失败
**What you expected to happen**:
启动成功
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
Error occurred while starting dev mode
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
nocalhost/internal/nhctl/controller.addAnnotationToDuplicate(0xc00197e600, 0xc001a3e540, 0x24, 0xc0007a9d70)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/duplicate.go:249 +0x46c
nocalhost/internal/nhctl/controller.(*Controller).ReplaceDuplicateModeImage(0xc00009fc30, 0x53da890, 0xc000136010, 0x6341360, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/duplicate.go:109 +0x15f0
nocalhost/internal/nhctl/controller.(*Controller).ReplaceImage(0xc00009fc30, 0x53da890, 0xc000136010, 0x6341360, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/service.go:563 +0x95
nocalhost/internal/nhctl/controller.(*DefaultController).ReplaceImage(0xc0005968d0, 0x53da890, 0xc000136010, 0x6341360, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/default_controller.go:18 +0x5b
nocalhost/cmd/nhctl/cmds/dev.(*DevStartOps).enterDevMode(0xc0018d9990, 0x7ff7bfeff8ad, 0x9, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/dev/dev_start.go:355 +0xa5c
nocalhost/cmd/nhctl/cmds/dev.(*DevStartOps).StartDevMode(0xc0018d9990, 0x7ff7bfeff7d7, 0x13, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/dev/dev_start.go:189 +0xae5
nocalhost/cmd/nhctl/cmds/dev.glob..func4(0x6324300, 0xc0002425a0, 0x1, 0x12)
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/dev/dev_start.go:113 +0x7b
github.com/spf13/cobra.(*Command).execute(0x6324300, 0xc000242480, 0x12, 0x12, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:860 +0xe5d
github.com/spf13/cobra.(*Command).ExecuteC(0x6321880, 0x6324300, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:974 +0x765
github.com/spf13/cobra.(*Command).Execute(0x6321880, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:902 +0x3b
nocalhost/cmd/nhctl/cmds.Execute()
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/root.go:147 +0x2c5
main.main()
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/nhctl.go:13 +0x25

```
**Environment**:
- OS:  Macos 12.3(21E230)
- nhctl version (use `nchtl version` command):
```
nhctl: Nocalhost CLI
    Version: v0.6.18
    Branch: HEAD
    Git commit: bee9765791752e00c75e88495ddbc5392e16d918
    Built time: Mon Apr 18 07:07:37 2022
    Built OS/Arch: darwin/amd64
    Built Go version: go1.16.7
```
- helm version (use `helm version` command): 没有用

- kubectl version (use `kubectl version` command):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"d966b365d87fb2783deab0d244047d340f1be146", GitTreeState:"clean", BuildDate:"2022-01-19T01:10:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by anurnomeru** [comment]
@wencaiwulue

**Comment by geek-dc** [comment]
这个问题怎么解决？我也遇到了

**Comment by wencaiwulue** [comment]
这个应该已经修好了，麻烦使用最新的 nhctl 以及镜像。

**Comment by keniushadu** [comment]
> 这个应该已经修好了，麻烦使用最新的 nhctl 以及镜像。

Roll backing dev mode...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
nocalhost/internal/nhctl/controller.addAnnotationToDuplicate(0x1400105c900, 0x140025fadb0, 0x24, 0x140009780f0)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/duplicate.go:250 +0x364
nocalhost/internal/nhctl/controller.(*Controller).ReplaceDuplicateModeImage(0x140001d1080, 0x107fb7c30, 0x140001a2010, 0x10900dea0, 0x14000100000, 0x14d)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/duplicate.go:110 +0x1b14
nocalhost/internal/nhctl/controller.(*Controller).ReplaceImage(0x140001d1080, 0x107fb7c30, 0x140001a2010, 0x10900dea0, 0x107bc2201, 0x14000a025e0)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/service.go:563 +0xb4
nocalhost/internal/nhctl/controller.(*DefaultController).ReplaceImage(0x14000a025e0, 0x107fb7c30, 0x140001a2010, 0x10900dea0, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/controller/default_controller.go:18 +0x44
nocalhost/cmd/nhctl/cmds/dev.(*DevStartOps).enterDevMode(0x14003247d10, 0x16b2ab304, 0x9, 0x0, 0x0)
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/dev/dev_start.go:355 +0x45c
nocalhost/cmd/nhctl/cmds/dev.(*DevStartOps).StartDevMode(0x14003247d10, 0x16b2ab232, 0x10, 0x104cff170, 0x14000859d10)
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/dev/dev_start.go:189 +0x260
nocalhost/cmd/nhctl/cmds/dev.glob..func4(0x108ff0e80, 0x1400000aea0, 0x1, 0x12)
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/dev/dev_start.go:113 +0x60
github.com/spf13/cobra.(*Command).execute(0x108ff0e80, 0x1400000ad80, 0x12, 0x12, 0x108ff0e80, 0x1400000ad80)
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:860 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x108fee400, 0x109924a68, 0x14000859f28, 0x104b59298)
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:974 +0x264
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:902
nocalhost/cmd/nhctl/cmds.Execute()
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/root.go:147 +0x4c
main.main()
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/nhctl.go:13 +0x20
